apiVersion: v1
kind: Service
metadata:
  name: {{ include "insurelytics.fullname" . }}-backend
  labels:
    app: {{ include "insurelytics.name" . }}
    component: backend
spec:
  type: ClusterIP
  selector:
    app: {{ include "insurelytics.name" . }}
    component: backend
  ports:
    - port: 8081
      targetPort: http
      protocol: TCP
      name: http