apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "insurelytics.fullname" . }}-frontend
  labels:
    app: {{ include "insurelytics.name" . }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "insurelytics.name" . }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ include "insurelytics.name" . }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: VITE_API_BASE_URL
              value: {{ .Values.frontend.env.VITE_API_BASE_URL | quote }}
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5