apiVersion: v1
kind: Service
metadata:
  name: {{ include "insurelytics.fullname" . }}-frontend
  labels:
    app: {{ include "insurelytics.name" . }}
    component: frontend
spec:
  type: ClusterIP
  selector:
    app: {{ include "insurelytics.name" . }}
    component: frontend
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http