name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build backend
        run: |
          cd insurelytics-pro/backend
          ./mvnw -B test package -DskipTests

      - name: Build frontend
        run: |
          cd insurelytics-pro/frontend
          npm ci
          npm run build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push backend image
        run: |
          cd insurelytics-pro/backend
          docker build -t ghcr.io/${{ github.repository_owner }}/insurelytics-backend:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/insurelytics-backend:${{ github.sha }}

      - name: Build and push frontend image
        run: |
          cd insurelytics-pro/frontend
          docker build -t ghcr.io/${{ github.repository_owner }}/insurelytics-frontend:${{ github.sha }} .
          docker push ghcr.io/${{ github.repository_owner }}/insurelytics-frontend:${{ github.sha }}

      - name: Set up kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.DO_KUBE_CONFIG }}" | base64 -d > ~/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Deploy to Kubernetes via Helm
        run: |
          cd insurelytics-pro/helm
          helm upgrade --install insurelytics . \ 
            --set backend.image.repository=ghcr.io/${{ github.repository_owner }}/insurelytics-backend \ 
            --set backend.image.tag=${{ github.sha }} \ 
            --set frontend.image.repository=ghcr.io/${{ github.repository_owner }}/insurelytics-frontend \ 
            --set frontend.image.tag=${{ github.sha }}